// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Compute.Clusters.Item.Instances.Item.Remediations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTriggerQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "REMEDIATION_TRIGGER_MANUAL")]
        #pragma warning disable CS1591
        REMEDIATION_TRIGGER_MANUAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMEDIATION_TRIGGER_AUTOMATED")]
        #pragma warning disable CS1591
        REMEDIATION_TRIGGER_AUTOMATED,
        #pragma warning restore CS1591
    }
}
