// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Projects.Item.Configs;
using Soenneker.Together.OpenApiClient.Projects.Item.Endpoints;
using Soenneker.Together.OpenApiClient.Projects.Item.ModelsRequests;
using Soenneker.Together.OpenApiClient.Projects.Item.PlacementProfiles;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Together.OpenApiClient.Projects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{projectId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The configs property</summary>
        public global::Soenneker.Together.OpenApiClient.Projects.Item.Configs.ConfigsRequestBuilder Configs
        {
            get => new global::Soenneker.Together.OpenApiClient.Projects.Item.Configs.ConfigsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The endpoints property</summary>
        public global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.EndpointsRequestBuilder Endpoints
        {
            get => new global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.EndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The models property</summary>
        public global::Soenneker.Together.OpenApiClient.Projects.Item.ModelsRequests.ModelsRequestBuilder Models
        {
            get => new global::Soenneker.Together.OpenApiClient.Projects.Item.ModelsRequests.ModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The placementProfiles property</summary>
        public global::Soenneker.Together.OpenApiClient.Projects.Item.PlacementProfiles.PlacementProfilesRequestBuilder PlacementProfiles
        {
            get => new global::Soenneker.Together.OpenApiClient.Projects.Item.PlacementProfiles.PlacementProfilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
