// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>DCGM diagnostic depth. SHORT = readiness; MEDIUM = default; LONG = system validation; EXTENDED = memtest. An omitted value selects MEDIUM when enabled.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AcceptanceTestsParamsDcgmDiagLevel
    {
        [EnumMember(Value = "DCGM_DIAG_LEVEL_SHORT")]
        #pragma warning disable CS1591
        DcgmDiagLevelShort,
        #pragma warning restore CS1591
        [EnumMember(Value = "DCGM_DIAG_LEVEL_MEDIUM")]
        #pragma warning disable CS1591
        DcgmDiagLevelMedium,
        #pragma warning restore CS1591
        [EnumMember(Value = "DCGM_DIAG_LEVEL_LONG")]
        #pragma warning disable CS1591
        DcgmDiagLevelLong,
        #pragma warning restore CS1591
        [EnumMember(Value = "DCGM_DIAG_LEVEL_EXTENDED")]
        #pragma warning disable CS1591
        DcgmDiagLevelExtended,
        #pragma warning restore CS1591
    }
}
