// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AudioSpeechRequestModel_Wrapper_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cartesia/sonic")]
        #pragma warning disable CS1591
        CartesiaSonic,
        #pragma warning restore CS1591
        [EnumMember(Value = "hexgrad/Kokoro-82M")]
        #pragma warning disable CS1591
        HexgradKokoro82M,
        #pragma warning restore CS1591
        [EnumMember(Value = "canopylabs/orpheus-3b-0.1-ft")]
        #pragma warning disable CS1591
        CanopylabsOrpheus3b01Ft,
        #pragma warning restore CS1591
    }
}
