// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AudioTranscriptionSpeakerSegment : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>End time of the speaker segment in seconds</summary>
        public float? End { get; set; }
        /// <summary>Unique identifier for the speaker segment</summary>
        public int? Id { get; set; }
        /// <summary>The speaker identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpeakerId { get; set; }
#nullable restore
#else
        public string SpeakerId { get; set; }
#endif
        /// <summary>Start time of the speaker segment in seconds</summary>
        public float? Start { get; set; }
        /// <summary>The full text spoken by this speaker in this segment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>Array of words spoken by this speaker in this segment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionWord>? Words { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionWord> Words { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionSpeakerSegment"/> and sets the default values.
        /// </summary>
        public AudioTranscriptionSpeakerSegment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionSpeakerSegment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionSpeakerSegment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionSpeakerSegment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end", n => { End = n.GetFloatValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "speaker_id", n => { SpeakerId = n.GetStringValue(); } },
                { "start", n => { Start = n.GetFloatValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "words", n => { Words = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionWord>(global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionWord.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("end", End);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("speaker_id", SpeakerId);
            writer.WriteFloatValue("start", Start);
            writer.WriteStringValue("text", Text);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.AudioTranscriptionWord>("words", Words);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
