// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Audio encoding of response. Only applicable when response_format is raw or pcm. Cartesia models respect this parameter and support all values. Orpheus, Kokoro, and Minimax models always return pcm_s16le regardless of this setting.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AudioSpeechRequestResponseEncoding
    {
        [EnumMember(Value = "pcm_f32le")]
        #pragma warning disable CS1591
        PcmF32Le,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_s16le")]
        #pragma warning disable CS1591
        PcmS16Le,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_mulaw")]
        #pragma warning disable CS1591
        PcmMulaw,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_alaw")]
        #pragma warning disable CS1591
        PcmAlaw,
        #pragma warning restore CS1591
    }
}
