// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Current status of the batch job</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchJobStatus
    {
        [EnumMember(Value = "VALIDATING")]
        #pragma warning disable CS1591
        Validating,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROGRESS")]
        #pragma warning disable CS1591
        InProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
    }
}
