// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BillingUsageReport : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Billing month (YYYY-MM).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingPeriod { get; set; }
#nullable restore
#else
        public string BillingPeriod { get; set; }
#endif
        /// <summary>The currency property</summary>
        public global::Soenneker.Together.OpenApiClient.Models.UsdCurrency? Currency { get; set; }
        /// <summary>Time windows containing usage line items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.BillingUsageWindow>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.BillingUsageWindow> Data { get; set; }
#endif
        /// <summary>Start of the earliest time window with usage in the month (UTC, ISO 8601); null when the month has no usage.</summary>
        public DateTimeOffset? EarliestWindowStart { get; set; }
        /// <summary>Exclusive end of the latest time window with usage in the month (UTC, ISO 8601); null when the month has no usage. Describes the whole month, not the current page.</summary>
        public DateTimeOffset? LatestWindowEnd { get; set; }
        /// <summary>Opaque cursor for the next page; null when this is the last page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>The object property</summary>
        public global::Soenneker.Together.OpenApiClient.Models.ListObject? Object { get; set; }
        /// <summary>ID of the organization the report belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.BillingUsageReport"/> and sets the default values.
        /// </summary>
        public BillingUsageReport()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.BillingUsageReport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.BillingUsageReport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.BillingUsageReport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_period", n => { BillingPeriod = n.GetStringValue(); } },
                { "currency", n => { Currency = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.UsdCurrency>(); } },
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.BillingUsageWindow>(global::Soenneker.Together.OpenApiClient.Models.BillingUsageWindow.CreateFromDiscriminatorValue)?.AsList(); } },
                { "earliest_window_start", n => { EarliestWindowStart = n.GetDateTimeOffsetValue(); } },
                { "latest_window_end", n => { LatestWindowEnd = n.GetDateTimeOffsetValue(); } },
                { "next_cursor", n => { NextCursor = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.ListObject>(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("billing_period", BillingPeriod);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.UsdCurrency>("currency", Currency);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.BillingUsageWindow>("data", Data);
            writer.WriteDateTimeOffsetValue("earliest_window_start", EarliestWindowStart);
            writer.WriteDateTimeOffsetValue("latest_window_end", LatestWindowEnd);
            writer.WriteStringValue("next_cursor", NextCursor);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.ListObject>("object", Object);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
