// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Cluster phase.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClusterPhaseTransitionPhase
    {
        [EnumMember(Value = "CLUSTER_PHASE_QUEUED")]
        #pragma warning disable CS1591
        ClusterPhaseQueued,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_SCHEDULED")]
        #pragma warning disable CS1591
        ClusterPhaseScheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_WAITING_FOR_CONTROL_PLANE_NODES")]
        #pragma warning disable CS1591
        ClusterPhaseWaitingForControlPlaneNodes,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_WAITING_FOR_DATA_PLANE_NODES")]
        #pragma warning disable CS1591
        ClusterPhaseWaitingForDataPlaneNodes,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_WAITING_FOR_SUBNET")]
        #pragma warning disable CS1591
        ClusterPhaseWaitingForSubnet,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_WAITING_FOR_SHARED_VOLUME")]
        #pragma warning disable CS1591
        ClusterPhaseWaitingForSharedVolume,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_WAITING_FOR_AUTO_SCALER")]
        #pragma warning disable CS1591
        ClusterPhaseWaitingForAutoScaler,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_INSTALLING_DRIVERS")]
        #pragma warning disable CS1591
        ClusterPhaseInstallingDrivers,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_RUNNING_ACCEPTANCE_TESTS")]
        #pragma warning disable CS1591
        ClusterPhaseRunningAcceptanceTests,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_ACCEPTANCE_TESTS_FAILED")]
        #pragma warning disable CS1591
        ClusterPhaseAcceptanceTestsFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_RUNNING_NCCL_TESTS")]
        #pragma warning disable CS1591
        ClusterPhaseRunningNcclTests,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_NCCL_TESTS_FAILED")]
        #pragma warning disable CS1591
        ClusterPhaseNcclTestsFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_READY")]
        #pragma warning disable CS1591
        ClusterPhaseReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_PAUSED")]
        #pragma warning disable CS1591
        ClusterPhasePaused,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_ON_DEMAND_COMPUTE_PAUSED")]
        #pragma warning disable CS1591
        ClusterPhaseOnDemandComputePaused,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_DEGRADED")]
        #pragma warning disable CS1591
        ClusterPhaseDegraded,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLUSTER_PHASE_DELETING")]
        #pragma warning disable CS1591
        ClusterPhaseDeleting,
        #pragma warning restore CS1591
    }
}
