// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CompletionChoicesData_item : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The finish_reason property</summary>
        public global::Soenneker.Together.OpenApiClient.Models.FinishReason? FinishReason { get; set; }
        /// <summary>The logprobs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.LogprobsPart? Logprobs { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.LogprobsPart Logprobs { get; set; }
#endif
        /// <summary>The seed property</summary>
        public int? Seed { get; set; }
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.CompletionChoicesData_item"/> and sets the default values.
        /// </summary>
        public CompletionChoicesData_item()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.CompletionChoicesData_item"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.CompletionChoicesData_item CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.CompletionChoicesData_item();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "finish_reason", n => { FinishReason = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.FinishReason>(); } },
                { "logprobs", n => { Logprobs = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.LogprobsPart>(global::Soenneker.Together.OpenApiClient.Models.LogprobsPart.CreateFromDiscriminatorValue); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.FinishReason>("finish_reason", FinishReason);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.LogprobsPart>("logprobs", Logprobs);
            writer.WriteIntValue("seed", Seed);
            writer.WriteStringValue("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
