// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CompletionRequestModel_Wrapper_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "meta-llama/Llama-2-70b-hf")]
        #pragma warning disable CS1591
        MetaLlamaLlama270bHf,
        #pragma warning restore CS1591
        [EnumMember(Value = "mistralai/Mistral-7B-v0.1")]
        #pragma warning disable CS1591
        MistralaiMistral7BV01,
        #pragma warning restore CS1591
        [EnumMember(Value = "mistralai/Mixtral-8x7B-v0.1")]
        #pragma warning disable CS1591
        MistralaiMixtral8x7BV01,
        #pragma warning restore CS1591
        [EnumMember(Value = "Meta-Llama/Llama-Guard-7b")]
        #pragma warning disable CS1591
        MetaLlamaLlamaGuard7b,
        #pragma warning restore CS1591
    }
}
