// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Branch2"/>, <see cref="global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Wrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompletionRequestModel : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Branch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Branch2? CompletionRequestModelBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Branch2 CompletionRequestModelBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Wrapper? CompletionRequestModelWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Wrapper CompletionRequestModelWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel();
            result.CompletionRequestModelBranch2 = new global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Branch2();
            result.CompletionRequestModelWrapper = new global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Wrapper();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CompletionRequestModelBranch2 != null || CompletionRequestModelWrapper != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionRequestModelBranch2, CompletionRequestModelWrapper);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.CompletionRequestModel_Branch2>(null, CompletionRequestModelBranch2, CompletionRequestModelWrapper);
        }
    }
}
#pragma warning restore CS0618
