// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CompletionRequestSafetyModel_Wrapper_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Meta-Llama/Llama-Guard-7b")]
        #pragma warning disable CS1591
        MetaLlamaLlamaGuard7b,
        #pragma warning restore CS1591
    }
}
