// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Type is the content type (currently only &quot;files&quot; is supported which allows preloading files uploaded via Files API into the volume)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateVolumeRequestContent_type
    {
        [EnumMember(Value = "files")]
        #pragma warning disable CS1591
        Files,
        #pragma warning restore CS1591
    }
}
