// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateDeploymentRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Args overrides the container&apos;s CMD. Provide as an array of arguments (e.g., [&quot;python&quot;, &quot;app.py&quot;])</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Args { get; set; }
#nullable restore
#else
        public List<string> Args { get; set; }
#endif
        /// <summary>&quot;Autoscaling configuration. Example: {\&quot;metric\&quot;: \&quot;QueueBacklogPerWorker\&quot;, \&quot;target\&quot;: 1.01} to scale based on queue backlog. Omit or set to null to disable autoscaling&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequestAutoscaling? Autoscaling { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequestAutoscaling Autoscaling { get; set; }
#endif
        /// <summary>Command overrides the container&apos;s ENTRYPOINT. Provide as an array (e.g., [&quot;/bin/sh&quot;, &quot;-c&quot;])</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Command { get; set; }
#nullable restore
#else
        public List<string> Command { get; set; }
#endif
        /// <summary>CPU is the number of CPU cores to allocate per container instance (e.g., 0.1 = 100 milli cores)</summary>
        public double? Cpu { get; set; }
        /// <summary>Description is an optional human-readable description of your deployment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>EnvironmentVariables is a list of environment variables to set in the container. Each must have a name and either a value or value_from_secret</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.EnvironmentVariable>? EnvironmentVariables { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.EnvironmentVariable> EnvironmentVariables { get; set; }
#endif
        /// <summary>GPUCount is the number of GPUs to allocate per container instance. Defaults to 0 if not specified</summary>
        public int? GpuCount { get; set; }
        /// <summary>GPUType specifies the GPU hardware to use (e.g., &quot;h100-80gb&quot;).</summary>
        public global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequest_gpu_type? GpuType { get; set; }
        /// <summary>HealthCheckPath is the HTTP path for health checks (e.g., &quot;/health&quot;). If set, the platform will check this endpoint to determine container health</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthCheckPath { get; set; }
#nullable restore
#else
        public string HealthCheckPath { get; set; }
#endif
        /// <summary>Image is the container image to deploy from registry.together.ai.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image { get; set; }
#nullable restore
#else
        public string Image { get; set; }
#endif
        /// <summary>MaxReplicas is the maximum number of container instances that can be scaled up to. If not set, will be set to MinReplicas</summary>
        public int? MaxReplicas { get; set; }
        /// <summary>Memory is the amount of RAM to allocate per container instance in GiB (e.g., 0.5 = 512MiB)</summary>
        public double? Memory { get; set; }
        /// <summary>MinReplicas is the minimum number of container instances to run. Defaults to 1 if not specified</summary>
        public int? MinReplicas { get; set; }
        /// <summary>Name is the unique identifier for your deployment. Must contain only alphanumeric characters, underscores, or hyphens (1-100 characters)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Port is the container port your application listens on (e.g., 8080 for web servers). Required if your application serves traffic</summary>
        public int? Port { get; set; }
        /// <summary>Storage is the amount of ephemeral disk storage to allocate per container instance (e.g., 10 = 10GiB)</summary>
        public int? Storage { get; set; }
        /// <summary>TerminationGracePeriodSeconds is the time in seconds to wait for graceful shutdown before forcefully terminating the replica</summary>
        public int? TerminationGracePeriodSeconds { get; set; }
        /// <summary>Volumes is a list of volume mounts to attach to the container. Each mount must reference an existing volume by name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.VolumeMount>? Volumes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.VolumeMount> Volumes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequest"/> and sets the default values.
        /// </summary>
        public CreateDeploymentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "args", n => { Args = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "autoscaling", n => { Autoscaling = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequestAutoscaling>(global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequestAutoscaling.CreateFromDiscriminatorValue); } },
                { "command", n => { Command = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "cpu", n => { Cpu = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "environment_variables", n => { EnvironmentVariables = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.EnvironmentVariable>(global::Soenneker.Together.OpenApiClient.Models.EnvironmentVariable.CreateFromDiscriminatorValue)?.AsList(); } },
                { "gpu_count", n => { GpuCount = n.GetIntValue(); } },
                { "gpu_type", n => { GpuType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequest_gpu_type>(); } },
                { "health_check_path", n => { HealthCheckPath = n.GetStringValue(); } },
                { "image", n => { Image = n.GetStringValue(); } },
                { "max_replicas", n => { MaxReplicas = n.GetIntValue(); } },
                { "memory", n => { Memory = n.GetDoubleValue(); } },
                { "min_replicas", n => { MinReplicas = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "port", n => { Port = n.GetIntValue(); } },
                { "storage", n => { Storage = n.GetIntValue(); } },
                { "termination_grace_period_seconds", n => { TerminationGracePeriodSeconds = n.GetIntValue(); } },
                { "volumes", n => { Volumes = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VolumeMount>(global::Soenneker.Together.OpenApiClient.Models.VolumeMount.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("args", Args);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequestAutoscaling>("autoscaling", Autoscaling);
            writer.WriteCollectionOfPrimitiveValues<string>("command", Command);
            writer.WriteDoubleValue("cpu", Cpu);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.EnvironmentVariable>("environment_variables", EnvironmentVariables);
            writer.WriteIntValue("gpu_count", GpuCount);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.CreateDeploymentRequest_gpu_type>("gpu_type", GpuType);
            writer.WriteStringValue("health_check_path", HealthCheckPath);
            writer.WriteStringValue("image", Image);
            writer.WriteIntValue("max_replicas", MaxReplicas);
            writer.WriteDoubleValue("memory", Memory);
            writer.WriteIntValue("min_replicas", MinReplicas);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("port", Port);
            writer.WriteIntValue("storage", Storage);
            writer.WriteIntValue("termination_grace_period_seconds", TerminationGracePeriodSeconds);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VolumeMount>("volumes", Volumes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
