// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Endpoint-wide usage and performance analytics with optional time-series and per-deployment breakdowns.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeAnalyticsData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Per-deployment analytics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.DeDeploymentAnalyticsData>? DeploymentAnalytics { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.DeDeploymentAnalyticsData> DeploymentAnalytics { get; set; }
#endif
        /// <summary>ID of the endpoint summarized by these analytics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndpointId { get; set; }
#nullable restore
#else
        public string EndpointId { get; set; }
#endif
        /// <summary>Aggregated metrics over the time range.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsDataMetrics? Metrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsDataMetrics Metrics { get; set; }
#endif
        /// <summary>Closed-open time range used by metrics and analytics responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange? TimeRange { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange TimeRange { get; set; }
#endif
        /// <summary>Per-bucket metric samples, included only when `includeTimeSeries` is true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.DeTimeSeriesDataPoint>? TimeSeries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.DeTimeSeriesDataPoint> TimeSeries { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsData"/> and sets the default values.
        /// </summary>
        public DeAnalyticsData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deploymentAnalytics", n => { DeploymentAnalytics = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeDeploymentAnalyticsData>(global::Soenneker.Together.OpenApiClient.Models.DeDeploymentAnalyticsData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "endpointId", n => { EndpointId = n.GetStringValue(); } },
                { "metrics", n => { Metrics = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsDataMetrics>(global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsDataMetrics.CreateFromDiscriminatorValue); } },
                { "timeRange", n => { TimeRange = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange>(global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange.CreateFromDiscriminatorValue); } },
                { "timeSeries", n => { TimeSeries = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeTimeSeriesDataPoint>(global::Soenneker.Together.OpenApiClient.Models.DeTimeSeriesDataPoint.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeDeploymentAnalyticsData>("deploymentAnalytics", DeploymentAnalytics);
            writer.WriteStringValue("endpointId", EndpointId);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeAnalyticsDataMetrics>("metrics", Metrics);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange>("timeRange", TimeRange);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeTimeSeriesDataPoint>("timeSeries", TimeSeries);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
