// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Request body for creating multipart upload URLs for model files.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeCreateUploadRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Base model identifier for a newly created derived model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseModelId { get; set; }
#nullable restore
#else
        public string BaseModelId { get; set; }
#endif
        /// <summary>Relationship between the new model and its base model.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestBaseRelation? BaseRelation { get; set; }
        /// <summary>Human-readable model description applied when a model is created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Draft speculator architecture for speculator model uploads.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestDraftSpeculatorType? DraftSpeculatorType { get; set; }
        /// <summary>Files that need upload URLs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestFile>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestFile> Files { get; set; }
#endif
        /// <summary>Existing model volume object identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>Name for a new model object created by the upload.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectName { get; set; }
#nullable restore
#else
        public string ObjectName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequest"/> and sets the default values.
        /// </summary>
        public DeCreateUploadRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseModelId", n => { BaseModelId = n.GetStringValue(); } },
                { "baseRelation", n => { BaseRelation = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestBaseRelation>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "draftSpeculatorType", n => { DraftSpeculatorType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestDraftSpeculatorType>(); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestFile>(global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestFile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "objectId", n => { ObjectId = n.GetStringValue(); } },
                { "objectName", n => { ObjectName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("baseModelId", BaseModelId);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestBaseRelation>("baseRelation", BaseRelation);
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestDraftSpeculatorType>("draftSpeculatorType", DraftSpeculatorType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeCreateUploadRequestFile>("files", Files);
            writer.WriteStringValue("objectId", ObjectId);
            writer.WriteStringValue("objectName", ObjectName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
