// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Sampling strategy and optional initial targets for mirroring endpoint requests without affecting client responses.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeCreateShadowExperimentRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Human-readable shadow experiment name, unique within the endpoint. At most 256 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Endpoint source and sampling configuration for the experiment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequestSource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequestSource Source { get; set; }
#endif
        /// <summary>Optional initial target deployments. At most 100 targets; manage later changes through the target APIs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentTargetRequest>? Targets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentTargetRequest> Targets { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequest"/> and sets the default values.
        /// </summary>
        public DeCreateShadowExperimentRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequestSource>(global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequestSource.CreateFromDiscriminatorValue); } },
                { "targets", n => { Targets = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentTargetRequest>(global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentTargetRequest.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentRequestSource>("source", Source);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeCreateShadowExperimentTargetRequest>("targets", Targets);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
