// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Draft speculator architecture for speculator model uploads.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeCreateUploadRequestDraftSpeculatorType
    {
        [EnumMember(Value = "DRAFT_SPECULATOR_TYPE_EAGLE")]
        #pragma warning disable CS1591
        DraftSpeculatorTypeEagle,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRAFT_SPECULATOR_TYPE_PHOENIX")]
        #pragma warning disable CS1591
        DraftSpeculatorTypePhoenix,
        #pragma warning restore CS1591
    }
}
