// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>High-level lifecycle state.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeDeploymentStatusState
    {
        [EnumMember(Value = "DEPLOYMENT_STATE_PROVISIONING")]
        #pragma warning disable CS1591
        DeploymentStateProvisioning,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_STATE_READY")]
        #pragma warning disable CS1591
        DeploymentStateReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_STATE_SCALING")]
        #pragma warning disable CS1591
        DeploymentStateScaling,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_STATE_DEGRADED")]
        #pragma warning disable CS1591
        DeploymentStateDegraded,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_STATE_FAILED")]
        #pragma warning disable CS1591
        DeploymentStateFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_STATE_STOPPED")]
        #pragma warning disable CS1591
        DeploymentStateStopped,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_STATE_STOPPING")]
        #pragma warning disable CS1591
        DeploymentStateStopping,
        #pragma warning restore CS1591
    }
}
