// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Operational metrics for one deployment under an endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeDeploymentMetrics : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the deployment summarized by these metrics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploymentId { get; set; }
#nullable restore
#else
        public string DeploymentId { get; set; }
#endif
        /// <summary>ID of the deployment&apos;s parent endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndpointId { get; set; }
#nullable restore
#else
        public string EndpointId { get; set; }
#endif
        /// <summary>Error rate and aggregate counts by error type. Individual error samples are not included.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeErrorMetrics? ErrorMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeErrorMetrics ErrorMetrics { get; set; }
#endif
        /// <summary>Time-to-first-token, end-to-end, and inter-token latency percentiles in milliseconds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeLatencyMetrics? LatencyMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeLatencyMetrics LatencyMetrics { get; set; }
#endif
        /// <summary>Request counts, rate, and status-code distribution over a time range.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeRequestMetrics? RequestMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeRequestMetrics RequestMetrics { get; set; }
#endif
        /// <summary>Average compute, memory, and network utilization for replicas over a time range.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeResourceUtilization? ResourceUtilization { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeResourceUtilization ResourceUtilization { get; set; }
#endif
        /// <summary>Token, request, and batching throughput over a time range.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics? ThroughputMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics ThroughputMetrics { get; set; }
#endif
        /// <summary>Closed-open time range used by metrics and analytics responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange? TimeRange { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange TimeRange { get; set; }
#endif
        /// <summary>Aggregate and per-request token usage over a time range.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeTokenMetrics? TokenMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeTokenMetrics TokenMetrics { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeDeploymentMetrics"/> and sets the default values.
        /// </summary>
        public DeDeploymentMetrics()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeDeploymentMetrics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeDeploymentMetrics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeDeploymentMetrics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deploymentId", n => { DeploymentId = n.GetStringValue(); } },
                { "endpointId", n => { EndpointId = n.GetStringValue(); } },
                { "errorMetrics", n => { ErrorMetrics = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeErrorMetrics>(global::Soenneker.Together.OpenApiClient.Models.DeErrorMetrics.CreateFromDiscriminatorValue); } },
                { "latencyMetrics", n => { LatencyMetrics = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeLatencyMetrics>(global::Soenneker.Together.OpenApiClient.Models.DeLatencyMetrics.CreateFromDiscriminatorValue); } },
                { "requestMetrics", n => { RequestMetrics = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeRequestMetrics>(global::Soenneker.Together.OpenApiClient.Models.DeRequestMetrics.CreateFromDiscriminatorValue); } },
                { "resourceUtilization", n => { ResourceUtilization = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeResourceUtilization>(global::Soenneker.Together.OpenApiClient.Models.DeResourceUtilization.CreateFromDiscriminatorValue); } },
                { "throughputMetrics", n => { ThroughputMetrics = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics>(global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics.CreateFromDiscriminatorValue); } },
                { "timeRange", n => { TimeRange = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange>(global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange.CreateFromDiscriminatorValue); } },
                { "tokenMetrics", n => { TokenMetrics = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeTokenMetrics>(global::Soenneker.Together.OpenApiClient.Models.DeTokenMetrics.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("deploymentId", DeploymentId);
            writer.WriteStringValue("endpointId", EndpointId);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeErrorMetrics>("errorMetrics", ErrorMetrics);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeLatencyMetrics>("latencyMetrics", LatencyMetrics);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeRequestMetrics>("requestMetrics", RequestMetrics);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeResourceUtilization>("resourceUtilization", ResourceUtilization);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics>("throughputMetrics", ThroughputMetrics);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricsTimeRange>("timeRange", TimeRange);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeTokenMetrics>("tokenMetrics", TokenMetrics);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
