// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Details about a dedicated endpoint deployment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DedicatedEndpoint : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Configuration for automatic scaling of replicas based on demand.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.Autoscaling? Autoscaling { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.Autoscaling Autoscaling { get; set; }
#endif
        /// <summary>Timestamp when the endpoint was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Human-readable name for the endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The hardware configuration used for this endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hardware { get; set; }
#nullable restore
#else
        public string Hardware { get; set; }
#endif
        /// <summary>Unique identifier for the endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The model deployed on this endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>System name for the endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The object type, which is always `endpoint`.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_object? Object { get; set; }
        /// <summary>The owner of this endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>Current state of the endpoint</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_state? State { get; set; }
        /// <summary>The type of endpoint</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint"/> and sets the default values.
        /// </summary>
        public DedicatedEndpoint()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoscaling", n => { Autoscaling = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.Autoscaling>(global::Soenneker.Together.OpenApiClient.Models.Autoscaling.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "hardware", n => { Hardware = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_object>(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_state>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.Autoscaling>("autoscaling", Autoscaling);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteStringValue("hardware", Hardware);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_object>("object", Object);
            writer.WriteStringValue("owner", Owner);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_state>("state", State);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DedicatedEndpoint_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
