// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Metric gate evaluated during a rollout.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeMetricRule : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Required metric name as exported to the observability backend.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Percentile value, such as 99. Set only when stat is METRIC_STAT_TYPE_PERCENTILE.</summary>
        public int? Percentile { get; set; }
        /// <summary>Regression evaluation criteria. Mutually exclusive with thresholdCheck.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleRegressionCheck? RegressionCheck { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleRegressionCheck RegressionCheck { get; set; }
#endif
        /// <summary>Required aggregation used for the metric.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleStat? Stat { get; set; }
        /// <summary>Threshold evaluation criteria. Mutually exclusive with regressionCheck.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleThresholdCheck? ThresholdCheck { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleThresholdCheck ThresholdCheck { get; set; }
#endif
        /// <summary>Optional query window for the metric. Defaults to the step soak duration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Window { get; set; }
#nullable restore
#else
        public string Window { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeMetricRule"/> and sets the default values.
        /// </summary>
        public DeMetricRule()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeMetricRule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeMetricRule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeMetricRule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue(); } },
                { "percentile", n => { Percentile = n.GetIntValue(); } },
                { "regressionCheck", n => { RegressionCheck = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleRegressionCheck>(global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleRegressionCheck.CreateFromDiscriminatorValue); } },
                { "stat", n => { Stat = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleStat>(); } },
                { "thresholdCheck", n => { ThresholdCheck = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleThresholdCheck>(global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleThresholdCheck.CreateFromDiscriminatorValue); } },
                { "window", n => { Window = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("percentile", Percentile);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleRegressionCheck>("regressionCheck", RegressionCheck);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleStat>("stat", Stat);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeMetricRuleThresholdCheck>("thresholdCheck", ThresholdCheck);
            writer.WriteStringValue("window", Window);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
