// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Architecture, size, precision, and speculative-decoding metadata for model weights.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeModelWeights : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Model architecture detected from the weight metadata.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Architecture { get; set; }
#nullable restore
#else
        public string Architecture { get; set; }
#endif
        /// <summary>Maximum context length reported by the model metadata.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContextLength { get; set; }
#nullable restore
#else
        public string ContextLength { get; set; }
#endif
        /// <summary>Draft-model speculator family for draft speculative decoding.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsDraftSpeculatorType? DraftSpeculatorType { get; set; }
        /// <summary>Model parameter count and precision breakdown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.DeModelParameters? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.DeModelParameters Parameters { get; set; }
#endif
        /// <summary>Speculative decoding mechanism for speculator weights.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsSpeculatorMechanism? SpeculatorMechanism { get; set; }
        /// <summary>&quot;Role of the weights: full model, speculative draft model, or LoRA adapter.&quot;</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeModelWeights"/> and sets the default values.
        /// </summary>
        public DeModelWeights()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeModelWeights"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeModelWeights CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeModelWeights();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "architecture", n => { Architecture = n.GetStringValue(); } },
                { "contextLength", n => { ContextLength = n.GetStringValue(); } },
                { "draftSpeculatorType", n => { DraftSpeculatorType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsDraftSpeculatorType>(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeModelParameters>(global::Soenneker.Together.OpenApiClient.Models.DeModelParameters.CreateFromDiscriminatorValue); } },
                { "speculatorMechanism", n => { SpeculatorMechanism = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsSpeculatorMechanism>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("architecture", Architecture);
            writer.WriteStringValue("contextLength", ContextLength);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsDraftSpeculatorType>("draftSpeculatorType", DraftSpeculatorType);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.DeModelParameters>("parameters", Parameters);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsSpeculatorMechanism>("speculatorMechanism", SpeculatorMechanism);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeModelWeightsType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
