// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Failure detail set when the rollout pauses, system-pauses, or aborts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeRolloutStatusCondition : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Step index where the condition arose. Step 0 serializes explicitly.</summary>
        public int? AtStep { get; set; }
        /// <summary>Category that classifies why the rollout stopped.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.DeRolloutConditionCategory? Category { get; set; }
        /// <summary>Human-readable explanation for the condition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Metrics observed at the failing gate, enriched with their criteria.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.DeMetricResult>? Metrics { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.DeMetricResult> Metrics { get; set; }
#endif
        /// <summary>Timestamp when the condition was observed.</summary>
        public DateTimeOffset? ObservedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeRolloutStatusCondition"/> and sets the default values.
        /// </summary>
        public DeRolloutStatusCondition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeRolloutStatusCondition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeRolloutStatusCondition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeRolloutStatusCondition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "atStep", n => { AtStep = n.GetIntValue(); } },
                { "category", n => { Category = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeRolloutConditionCategory>(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "metrics", n => { Metrics = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeMetricResult>(global::Soenneker.Together.OpenApiClient.Models.DeMetricResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "observedAt", n => { ObservedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("atStep", AtStep);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.DeRolloutConditionCategory>("category", Category);
            writer.WriteStringValue("message", Message);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.DeMetricResult>("metrics", Metrics);
            writer.WriteDateTimeOffsetValue("observedAt", ObservedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
