// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeSupportedModelCapabilitiesItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CAPABILITY_CHAT")]
        #pragma warning disable CS1591
        CapabilityChat,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAPABILITY_EMBEDDING")]
        #pragma warning disable CS1591
        CapabilityEmbedding,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAPABILITY_RERANKING")]
        #pragma warning disable CS1591
        CapabilityReranking,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAPABILITY_IMAGE_GENERATION")]
        #pragma warning disable CS1591
        CapabilityImageGeneration,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAPABILITY_VIDEO_GENERATION")]
        #pragma warning disable CS1591
        CapabilityVideoGeneration,
        #pragma warning restore CS1591
    }
}
