// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Token, request, and batching throughput over a time range.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeThroughputMetrics : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Average number of batches queued or in flight in the serving engine.</summary>
        public double? AvgBatchDepth { get; set; }
        /// <summary>Average number of requests processed in each runtime batch.</summary>
        public double? AvgBatchSize { get; set; }
        /// <summary>Average completed requests per second.</summary>
        public double? RequestsPerSecond { get; set; }
        /// <summary>Average generated tokens per second.</summary>
        public double? TokensPerSecond { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics"/> and sets the default values.
        /// </summary>
        public DeThroughputMetrics()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.DeThroughputMetrics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avgBatchDepth", n => { AvgBatchDepth = n.GetDoubleValue(); } },
                { "avgBatchSize", n => { AvgBatchSize = n.GetDoubleValue(); } },
                { "requestsPerSecond", n => { RequestsPerSecond = n.GetDoubleValue(); } },
                { "tokensPerSecond", n => { TokensPerSecond = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("avgBatchDepth", AvgBatchDepth);
            writer.WriteDoubleValue("avgBatchSize", AvgBatchSize);
            writer.WriteDoubleValue("requestsPerSecond", RequestsPerSecond);
            writer.WriteDoubleValue("tokensPerSecond", TokensPerSecond);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
