// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>The object type, which is always `embedding`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmbeddingsResponse_data_object
    {
        [EnumMember(Value = "embedding")]
        #pragma warning disable CS1591
        Embedding,
        #pragma warning restore CS1591
    }
}
