// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Minimum severity. Omit to disable severity filtering.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EndpointServiceListEndpointEventsMinLevelParameter
    {
        [EnumMember(Value = "LEVEL_DEBUG")]
        #pragma warning disable CS1591
        LevelDebug,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEVEL_INFO")]
        #pragma warning disable CS1591
        LevelInfo,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEVEL_WARN")]
        #pragma warning disable CS1591
        LevelWarn,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEVEL_ERROR")]
        #pragma warning disable CS1591
        LevelError,
        #pragma warning restore CS1591
    }
}
