// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EndpointServiceListEndpointEventsSourceKindsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SOURCE_KIND_ENDPOINT")]
        #pragma warning disable CS1591
        SourceKindEndpoint,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOURCE_KIND_DEPLOYMENT")]
        #pragma warning disable CS1591
        SourceKindDeployment,
        #pragma warning restore CS1591
    }
}
