// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>The type of evaluation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EvaluationJob_type
    {
        [EnumMember(Value = "classify")]
        #pragma warning disable CS1591
        Classify,
        #pragma warning restore CS1591
        [EnumMember(Value = "score")]
        #pragma warning disable CS1591
        Score,
        #pragma warning restore CS1591
        [EnumMember(Value = "compare")]
        #pragma warning disable CS1591
        Compare,
        #pragma warning restore CS1591
    }
}
