// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EvaluationScoreResults : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aggregated_scores property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResultsAggregatedScores? AggregatedScores { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResultsAggregatedScores AggregatedScores { get; set; }
#endif
        /// <summary>number of failed samples generated from model</summary>
        public double? FailedSamples { get; set; }
        /// <summary>Number of failed generations.</summary>
        public double? GenerationFailCount { get; set; }
        /// <summary>number of invalid scores generated from model</summary>
        public double? InvalidScoreCount { get; set; }
        /// <summary>Number of failed judge generations</summary>
        public double? JudgeFailCount { get; set; }
        /// <summary>Data File ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultFileId { get; set; }
#nullable restore
#else
        public string ResultFileId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResults"/> and sets the default values.
        /// </summary>
        public EvaluationScoreResults()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResults"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResults CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResults();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregated_scores", n => { AggregatedScores = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResultsAggregatedScores>(global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResultsAggregatedScores.CreateFromDiscriminatorValue); } },
                { "failed_samples", n => { FailedSamples = n.GetDoubleValue(); } },
                { "generation_fail_count", n => { GenerationFailCount = n.GetDoubleValue(); } },
                { "invalid_score_count", n => { InvalidScoreCount = n.GetDoubleValue(); } },
                { "judge_fail_count", n => { JudgeFailCount = n.GetDoubleValue(); } },
                { "result_file_id", n => { ResultFileId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.EvaluationScoreResultsAggregatedScores>("aggregated_scores", AggregatedScores);
            writer.WriteDoubleValue("failed_samples", FailedSamples);
            writer.WriteDoubleValue("generation_fail_count", GenerationFailCount);
            writer.WriteDoubleValue("invalid_score_count", InvalidScoreCount);
            writer.WriteDoubleValue("judge_fail_count", JudgeFailCount);
            writer.WriteStringValue("result_file_id", ResultFileId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
