// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Encoding of the file content. Use `string` for text files such as code, and `base64` for binary files, such as images.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExecuteRequest_files_encoding
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        String,
        #pragma warning restore CS1591
        [EnumMember(Value = "base64")]
        #pragma warning disable CS1591
        Base64,
        #pragma warning restore CS1591
    }
}
