// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutputType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "stdout")]
        #pragma warning disable CS1591
        Stdout,
        #pragma warning restore CS1591
        [EnumMember(Value = "stderr")]
        #pragma warning disable CS1591
        Stderr,
        #pragma warning restore CS1591
    }
}
