// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutputType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "display_data")]
        #pragma warning disable CS1591
        DisplayData,
        #pragma warning restore CS1591
        [EnumMember(Value = "execute_result")]
        #pragma warning disable CS1591
        ExecuteResult,
        #pragma warning restore CS1591
    }
}
