// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput"/>, <see cref="global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput"/>, <see cref="global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecuteResponseSuccessfulExecutionDataOutputsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput? ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput? ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput? ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItem();
            if("ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput = new global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput();
            }
            else if("ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput = new global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput();
            }
            else if("ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput = new global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput != null)
            {
                return ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput.GetFieldDeserializers();
            }
            else if(ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput != null)
            {
                return ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput.GetFieldDeserializers();
            }
            else if(ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput != null)
            {
                return ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput>(null, ExecuteResponseSuccessfulExecutionDataOutputsItemDisplayorExecuteOutput);
            }
            else if(ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput>(null, ExecuteResponseSuccessfulExecutionDataOutputsItemErrorOutput);
            }
            else if(ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput>(null, ExecuteResponseSuccessfulExecutionDataOutputsItemStreamOutput);
            }
        }
    }
}
#pragma warning restore CS0618
