// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>The purpose of the file</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FilePurpose
    {
        [EnumMember(Value = "fine-tune")]
        #pragma warning disable CS1591
        FineTune,
        #pragma warning restore CS1591
        [EnumMember(Value = "eval")]
        #pragma warning disable CS1591
        Eval,
        #pragma warning restore CS1591
        [EnumMember(Value = "eval-sample")]
        #pragma warning disable CS1591
        EvalSample,
        #pragma warning restore CS1591
        [EnumMember(Value = "eval-output")]
        #pragma warning disable CS1591
        EvalOutput,
        #pragma warning restore CS1591
        [EnumMember(Value = "eval-summary")]
        #pragma warning disable CS1591
        EvalSummary,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch-generated")]
        #pragma warning disable CS1591
        BatchGenerated,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch-api")]
        #pragma warning disable CS1591
        BatchApi,
        #pragma warning restore CS1591
    }
}
