// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Category of validation failure.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FileValidationReportErrorType
    {
        [EnumMember(Value = "INVALID_FORMAT")]
        #pragma warning disable CS1591
        InvalidFormat,
        #pragma warning restore CS1591
    }
}
