// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FinetuneEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "job_pending")]
        #pragma warning disable CS1591
        Job_pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_start")]
        #pragma warning disable CS1591
        Job_start,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_stopped")]
        #pragma warning disable CS1591
        Job_stopped,
        #pragma warning restore CS1591
        [EnumMember(Value = "model_downloading")]
        #pragma warning disable CS1591
        Model_downloading,
        #pragma warning restore CS1591
        [EnumMember(Value = "model_download_complete")]
        #pragma warning disable CS1591
        Model_download_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "training_data_downloading")]
        #pragma warning disable CS1591
        Training_data_downloading,
        #pragma warning restore CS1591
        [EnumMember(Value = "training_data_download_complete")]
        #pragma warning disable CS1591
        Training_data_download_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "validation_data_downloading")]
        #pragma warning disable CS1591
        Validation_data_downloading,
        #pragma warning restore CS1591
        [EnumMember(Value = "validation_data_download_complete")]
        #pragma warning disable CS1591
        Validation_data_download_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "wandb_init")]
        #pragma warning disable CS1591
        Wandb_init,
        #pragma warning restore CS1591
        [EnumMember(Value = "training_start")]
        #pragma warning disable CS1591
        Training_start,
        #pragma warning restore CS1591
        [EnumMember(Value = "checkpoint_save")]
        #pragma warning disable CS1591
        Checkpoint_save,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing_limit")]
        #pragma warning disable CS1591
        Billing_limit,
        #pragma warning restore CS1591
        [EnumMember(Value = "epoch_complete")]
        #pragma warning disable CS1591
        Epoch_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "training_complete")]
        #pragma warning disable CS1591
        Training_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "model_compressing")]
        #pragma warning disable CS1591
        Model_compressing,
        #pragma warning restore CS1591
        [EnumMember(Value = "model_compression_complete")]
        #pragma warning disable CS1591
        Model_compression_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "model_uploading")]
        #pragma warning disable CS1591
        Model_uploading,
        #pragma warning restore CS1591
        [EnumMember(Value = "model_upload_complete")]
        #pragma warning disable CS1591
        Model_upload_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_complete")]
        #pragma warning disable CS1591
        Job_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_error")]
        #pragma warning disable CS1591
        Job_error,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancel_requested")]
        #pragma warning disable CS1591
        Cancel_requested,
        #pragma warning restore CS1591
        [EnumMember(Value = "job_restarted")]
        #pragma warning disable CS1591
        Job_restarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "refund")]
        #pragma warning disable CS1591
        Refund,
        #pragma warning restore CS1591
        [EnumMember(Value = "warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
    }
}
