// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Together.OpenApiClient.Models.TrainingMethodDpo"/>, <see cref="global::Soenneker.Together.OpenApiClient.Models.TrainingMethodSft"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FinetuneResponseTruncatedTrainingMethod : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.TrainingMethodDpo"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.TrainingMethodDpo? TrainingMethodDpo { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.TrainingMethodDpo TrainingMethodDpo { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.TrainingMethodSft"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.TrainingMethodSft? TrainingMethodSft { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.TrainingMethodSft TrainingMethodSft { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.FinetuneResponseTruncatedTrainingMethod"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.FinetuneResponseTruncatedTrainingMethod CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Together.OpenApiClient.Models.FinetuneResponseTruncatedTrainingMethod();
            if("TrainingMethodDpo".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TrainingMethodDpo = new global::Soenneker.Together.OpenApiClient.Models.TrainingMethodDpo();
            }
            else if("TrainingMethodSft".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TrainingMethodSft = new global::Soenneker.Together.OpenApiClient.Models.TrainingMethodSft();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(TrainingMethodDpo != null)
            {
                return TrainingMethodDpo.GetFieldDeserializers();
            }
            else if(TrainingMethodSft != null)
            {
                return TrainingMethodSft.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(TrainingMethodDpo != null)
            {
                writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.TrainingMethodDpo>(null, TrainingMethodDpo);
            }
            else if(TrainingMethodSft != null)
            {
                writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.TrainingMethodSft>(null, TrainingMethodSft);
            }
        }
    }
}
#pragma warning restore CS0618
