// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Billing type for the cluster (RESERVED, ON_DEMAND, or SCHEDULED_CAPACITY).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GpuClusterInfoBillingType
    {
        [EnumMember(Value = "RESERVED")]
        #pragma warning disable CS1591
        Reserved,
        #pragma warning restore CS1591
        [EnumMember(Value = "ON_DEMAND")]
        #pragma warning disable CS1591
        OnDemand,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULED_CAPACITY")]
        #pragma warning disable CS1591
        ScheduledCapacity,
        #pragma warning restore CS1591
    }
}
