// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// GPU Cluster create request
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GPUClusterCreateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>RESERVED billing types allow you to specify the duration of the cluster reservation via the duration_days field.ON_DEMAND billing types will give you ownership of the cluster until you delete it.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_billing_type? BillingType { get; set; }
        /// <summary>Name of the GPU cluster.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClusterName { get; set; }
#nullable restore
#else
        public string ClusterName { get; set; }
#endif
        /// <summary>Type of cluster to create.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_cluster_type? ClusterType { get; set; }
        /// <summary>NVIDIA driver version to use in the cluster.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_driver_version? DriverVersion { get; set; }
        /// <summary>Duration in days to keep the cluster running.</summary>
        public int? DurationDays { get; set; }
        /// <summary>Type of GPU to use in the cluster</summary>
        public global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_gpu_type? GpuType { get; set; }
        /// <summary>Number of GPUs to allocate in the cluster. This must be multiple of 8. For example, 8, 16 or 24</summary>
        public int? NumGpus { get; set; }
        /// <summary>Region to create the GPU cluster in. Usable regions can be found from `client.clusters.list_regions()`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The shared_volume property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.GPUClustersSharedVolumeCreateRequest? SharedVolume { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.GPUClustersSharedVolumeCreateRequest SharedVolume { get; set; }
#endif
        /// <summary>ID of an existing volume to use with the cluster creation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VolumeId { get; set; }
#nullable restore
#else
        public string VolumeId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest"/> and sets the default values.
        /// </summary>
        public GPUClusterCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_type", n => { BillingType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_billing_type>(); } },
                { "cluster_name", n => { ClusterName = n.GetStringValue(); } },
                { "cluster_type", n => { ClusterType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_cluster_type>(); } },
                { "driver_version", n => { DriverVersion = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_driver_version>(); } },
                { "duration_days", n => { DurationDays = n.GetIntValue(); } },
                { "gpu_type", n => { GpuType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_gpu_type>(); } },
                { "num_gpus", n => { NumGpus = n.GetIntValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "shared_volume", n => { SharedVolume = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.GPUClustersSharedVolumeCreateRequest>(global::Soenneker.Together.OpenApiClient.Models.GPUClustersSharedVolumeCreateRequest.CreateFromDiscriminatorValue); } },
                { "volume_id", n => { VolumeId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_billing_type>("billing_type", BillingType);
            writer.WriteStringValue("cluster_name", ClusterName);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_cluster_type>("cluster_type", ClusterType);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_driver_version>("driver_version", DriverVersion);
            writer.WriteIntValue("duration_days", DurationDays);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.GPUClusterCreateRequest_gpu_type>("gpu_type", GpuType);
            writer.WriteIntValue("num_gpus", NumGpus);
            writer.WriteStringValue("region", Region);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.GPUClustersSharedVolumeCreateRequest>("shared_volume", SharedVolume);
            writer.WriteStringValue("volume_id", VolumeId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
