// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Hardware configuration details with optional availability status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HardwareWithStatus : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates the current availability status of a hardware configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.HardwareAvailability? Availability { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.HardwareAvailability Availability { get; set; }
#endif
        /// <summary>Unique identifier for the hardware configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The object type, which is always `hardware`.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.HardwareWithStatus_object? Object { get; set; }
        /// <summary>Pricing details for using an endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.EndpointPricing? Pricing { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.EndpointPricing Pricing { get; set; }
#endif
        /// <summary>Detailed specifications of a hardware configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.HardwareSpec? Specs { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.HardwareSpec Specs { get; set; }
#endif
        /// <summary>Timestamp of when the hardware status was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.HardwareWithStatus"/> and sets the default values.
        /// </summary>
        public HardwareWithStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.HardwareWithStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.HardwareWithStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.HardwareWithStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availability", n => { Availability = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.HardwareAvailability>(global::Soenneker.Together.OpenApiClient.Models.HardwareAvailability.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.HardwareWithStatus_object>(); } },
                { "pricing", n => { Pricing = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.EndpointPricing>(global::Soenneker.Together.OpenApiClient.Models.EndpointPricing.CreateFromDiscriminatorValue); } },
                { "specs", n => { Specs = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.HardwareSpec>(global::Soenneker.Together.OpenApiClient.Models.HardwareSpec.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.HardwareAvailability>("availability", Availability);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.HardwareWithStatus_object>("object", Object);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.EndpointPricing>("pricing", Pricing);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.HardwareSpec>("specs", Specs);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
