// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>The availability status of the hardware configuration</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HardwareAvailability_status
    {
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "unavailable")]
        #pragma warning disable CS1591
        Unavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "insufficient")]
        #pragma warning disable CS1591
        Insufficient,
        #pragma warning restore CS1591
    }
}
