// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>The object type, which is always `hardware`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HardwareWithStatus_object
    {
        [EnumMember(Value = "hardware")]
        #pragma warning disable CS1591
        Hardware,
        #pragma warning restore CS1591
    }
}
