// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HealthCheckServiceListPassiveHealthCheckAlertsSeverityFilterParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PHC_SEVERITY_INFO")]
        #pragma warning disable CS1591
        PhcSeverityInfo,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHC_SEVERITY_WARNING")]
        #pragma warning disable CS1591
        PhcSeverityWarning,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHC_SEVERITY_CRITICAL")]
        #pragma warning disable CS1591
        PhcSeverityCritical,
        #pragma warning restore CS1591
    }
}
