// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InstanceClusterConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>NVIDIA GPU Operator chart/version for the tenant cluster (e.g. v24.6.2). When omitted, a service default is applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GpuOperatorVersion { get; set; }
#nullable restore
#else
        public string GpuOperatorVersion { get; set; }
#endif
        /// <summary>The ingress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.ClusterIngressConfig? Ingress { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.ClusterIngressConfig Ingress { get; set; }
#endif
        /// <summary>The jumphost_enabled property</summary>
        public bool? JumphostEnabled { get; set; }
        /// <summary>The kubernetes_dashboard_enabled property</summary>
        public bool? KubernetesDashboardEnabled { get; set; }
        /// <summary>The load_balancer property</summary>
        public global::Soenneker.Together.OpenApiClient.Models.InstanceClusterConfigLoadBalancer? LoadBalancer { get; set; }
        /// <summary>NVIDIA Network Operator chart/version for the tenant cluster (e.g. v24.7.0). When omitted, a service default is applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetworkOperatorVersion { get; set; }
#nullable restore
#else
        public string NetworkOperatorVersion { get; set; }
#endif
        /// <summary>The observability property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.ObservabilityConfig? Observability { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.ObservabilityConfig Observability { get; set; }
#endif
        /// <summary>SlurmStartupScripts carries optional Slurm lifecycle scripts (prolog/epilog, init, extra conf).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.SlurmStartupScripts? SlurmStartupScripts { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.SlurmStartupScripts SlurmStartupScripts { get; set; }
#endif
        /// <summary>Whether this cluster uses a per-cluster SSH certificate authority for OIDC-signed SSH access.</summary>
        public bool? SshCaEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.InstanceClusterConfig"/> and sets the default values.
        /// </summary>
        public InstanceClusterConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.InstanceClusterConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.InstanceClusterConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.InstanceClusterConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gpu_operator_version", n => { GpuOperatorVersion = n.GetStringValue(); } },
                { "ingress", n => { Ingress = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.ClusterIngressConfig>(global::Soenneker.Together.OpenApiClient.Models.ClusterIngressConfig.CreateFromDiscriminatorValue); } },
                { "jumphost_enabled", n => { JumphostEnabled = n.GetBoolValue(); } },
                { "kubernetes_dashboard_enabled", n => { KubernetesDashboardEnabled = n.GetBoolValue(); } },
                { "load_balancer", n => { LoadBalancer = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.InstanceClusterConfigLoadBalancer>(); } },
                { "network_operator_version", n => { NetworkOperatorVersion = n.GetStringValue(); } },
                { "observability", n => { Observability = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.ObservabilityConfig>(global::Soenneker.Together.OpenApiClient.Models.ObservabilityConfig.CreateFromDiscriminatorValue); } },
                { "slurm_startup_scripts", n => { SlurmStartupScripts = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.SlurmStartupScripts>(global::Soenneker.Together.OpenApiClient.Models.SlurmStartupScripts.CreateFromDiscriminatorValue); } },
                { "ssh_ca_enabled", n => { SshCaEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("gpu_operator_version", GpuOperatorVersion);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.ClusterIngressConfig>("ingress", Ingress);
            writer.WriteBoolValue("jumphost_enabled", JumphostEnabled);
            writer.WriteBoolValue("kubernetes_dashboard_enabled", KubernetesDashboardEnabled);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.InstanceClusterConfigLoadBalancer>("load_balancer", LoadBalancer);
            writer.WriteStringValue("network_operator_version", NetworkOperatorVersion);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.ObservabilityConfig>("observability", Observability);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.SlurmStartupScripts>("slurm_startup_scripts", SlurmStartupScripts);
            writer.WriteBoolValue("ssh_ca_enabled", SshCaEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
