// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Only return checkpoints of this type. CHECKPOINT_TYPE_TRAINING is the full training state (weights and optimizer state), for resuming a training session with its optimizer state; CHECKPOINT_TYPE_INFERENCE is a model ready for serving or download, also added to your models. When set, it must be CHECKPOINT_TYPE_TRAINING or CHECKPOINT_TYPE_INFERENCE; when omitted, checkpoints of both types are returned.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListCheckpointsTypeParameter
    {
        [EnumMember(Value = "CHECKPOINT_TYPE_TRAINING")]
        #pragma warning disable CS1591
        CheckpointTypeTraining,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHECKPOINT_TYPE_INFERENCE")]
        #pragma warning disable CS1591
        CheckpointTypeInference,
        #pragma warning restore CS1591
    }
}
