// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListTrainingSessionsStatusParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TRAINING_SESSION_STATUS_CREATING")]
        #pragma warning disable CS1591
        TrainingSessionStatusCreating,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_SESSION_STATUS_RUNNING")]
        #pragma warning disable CS1591
        TrainingSessionStatusRunning,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_SESSION_STATUS_STOPPED")]
        #pragma warning disable CS1591
        TrainingSessionStatusStopped,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_SESSION_STATUS_STOPPING")]
        #pragma warning disable CS1591
        TrainingSessionStatusStopping,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_SESSION_STATUS_ERROR")]
        #pragma warning disable CS1591
        TrainingSessionStatusError,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_SESSION_STATUS_EXPIRED")]
        #pragma warning disable CS1591
        TrainingSessionStatusExpired,
        #pragma warning restore CS1591
    }
}
