// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>The object type, which is always `model`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModelInfo_object
    {
        [EnumMember(Value = "model")]
        #pragma warning disable CS1591
        Model,
        #pragma warning restore CS1591
    }
}
