// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Typed annotation content parsed from the legacy annotations bag.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PassiveHealthCheckAlertAnnotation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Static explanation for the alert.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; private set; }
#nullable restore
#else
        public string Description { get; private set; }
#endif
        /// <summary>Slurm node details when the alert was caused by unavailable Slurm nodes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationSlurmNodeUnavailable? SlurmNodeUnavailable { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationSlurmNodeUnavailable SlurmNodeUnavailable { get; set; }
#endif
        /// <summary>Per-firing summary line parsed from the evidence annotation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SummaryLine { get; private set; }
#nullable restore
#else
        public string SummaryLine { get; private set; }
#endif
        /// <summary>Alert title from the Alertmanager summary annotation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; private set; }
#nullable restore
#else
        public string Title { get; private set; }
#endif
        /// <summary>Xid-specific details when the alert was caused by NVIDIA Xid errors.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationXid? Xid { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationXid Xid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.PassiveHealthCheckAlertAnnotation"/> and sets the default values.
        /// </summary>
        public PassiveHealthCheckAlertAnnotation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.PassiveHealthCheckAlertAnnotation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.PassiveHealthCheckAlertAnnotation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.PassiveHealthCheckAlertAnnotation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "slurm_node_unavailable", n => { SlurmNodeUnavailable = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationSlurmNodeUnavailable>(global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationSlurmNodeUnavailable.CreateFromDiscriminatorValue); } },
                { "summary_line", n => { SummaryLine = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "xid", n => { Xid = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationXid>(global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationXid.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationSlurmNodeUnavailable>("slurm_node_unavailable", SlurmNodeUnavailable);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.PhcAnnotationXid>("xid", Xid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
