// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Format of the image response. Can be either a base64 string or a URL.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostImagesGenerations_response_format
    {
        [EnumMember(Value = "base64")]
        #pragma warning disable CS1591
        Base64,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
    }
}
