// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSizeOneOf2"/>, <see cref="int"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostFineTunesRequestBatchSize : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="int"/></summary>
        public int? Integer { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSizeOneOf2"/></summary>
        public global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSizeOneOf2? PostFineTunesRequestBatchSizeOneOf2 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSize"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSize CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSize();
            if(parseNode.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSizeOneOf2>() is global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSizeOneOf2 postFineTunesRequestBatchSizeOneOf2Value)
            {
                result.PostFineTunesRequestBatchSizeOneOf2 = postFineTunesRequestBatchSizeOneOf2Value;
            }
            else if(parseNode.GetIntValue() is int integerValue)
            {
                result.Integer = integerValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(PostFineTunesRequestBatchSizeOneOf2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.PostFineTunesRequestBatchSizeOneOf2>(null, PostFineTunesRequestBatchSizeOneOf2);
            }
            else if(Integer != null)
            {
                writer.WriteIntValue(null, Integer);
            }
        }
    }
}
#pragma warning restore CS0618
