// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Server-resolved configuration for a quantization job.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuantizationPipelineConfiguration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Qualified adapter model name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdapterModelName { get; set; }
#nullable restore
#else
        public string AdapterModelName { get; set; }
#endif
        /// <summary>Project that owns the adapter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdapterProjectId { get; set; }
#nullable restore
#else
        public string AdapterProjectId { get; set; }
#endif
        /// <summary>Adapter revision selected for preparation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdapterRevisionId { get; set; }
#nullable restore
#else
        public string AdapterRevisionId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Qualified name of the base model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseModelName { get; set; }
#nullable restore
#else
        public string BaseModelName { get; set; }
#endif
        /// <summary>Model object ID of the adapter&apos;s base model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseObjectId { get; set; }
#nullable restore
#else
        public string BaseObjectId { get; set; }
#endif
        /// <summary>Revision ID of the adapter&apos;s base model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseRevisionId { get; set; }
#nullable restore
#else
        public string BaseRevisionId { get; set; }
#endif
        /// <summary>User whose scope is used to fetch the adapter weights.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.QuantizationPipelineConfiguration"/> and sets the default values.
        /// </summary>
        public QuantizationPipelineConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.QuantizationPipelineConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.QuantizationPipelineConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.QuantizationPipelineConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adapter_model_name", n => { AdapterModelName = n.GetStringValue(); } },
                { "adapter_project_id", n => { AdapterProjectId = n.GetStringValue(); } },
                { "adapter_revision_id", n => { AdapterRevisionId = n.GetStringValue(); } },
                { "base_model_name", n => { BaseModelName = n.GetStringValue(); } },
                { "base_object_id", n => { BaseObjectId = n.GetStringValue(); } },
                { "base_revision_id", n => { BaseRevisionId = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("adapter_model_name", AdapterModelName);
            writer.WriteStringValue("adapter_project_id", AdapterProjectId);
            writer.WriteStringValue("adapter_revision_id", AdapterRevisionId);
            writer.WriteStringValue("base_model_name", BaseModelName);
            writer.WriteStringValue("base_object_id", BaseObjectId);
            writer.WriteStringValue("base_revision_id", BaseRevisionId);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
