// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>&quot;Remediation mode specifies how the remediation should be performed.- `REMEDIATION_MODE_VM_ONLY`: Deletes the VM and provisions a new one on any available host.- `REMEDIATION_MODE_HOST_AWARE`: Cordons the host, deletes the VM, and provisions a new one on a different host.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Remediation_mode
    {
        [EnumMember(Value = "REMEDIATION_MODE_VM_ONLY")]
        #pragma warning disable CS1591
        REMEDIATION_MODE_VM_ONLY,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMEDIATION_MODE_HOST_AWARE")]
        #pragma warning disable CS1591
        REMEDIATION_MODE_HOST_AWARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMEDIATION_MODE_EVICT_WITHOUT_REPLACEMENT")]
        #pragma warning disable CS1591
        REMEDIATION_MODE_EVICT_WITHOUT_REPLACEMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMEDIATION_MODE_REBOOT_VM")]
        #pragma warning disable CS1591
        REMEDIATION_MODE_REBOOT_VM,
        #pragma warning restore CS1591
    }
}
