// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>The object type, which is always `revision_event`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RevisionEventItemObject
    {
        [EnumMember(Value = "revision_event")]
        #pragma warning disable CS1591
        RevisionEvent,
        #pragma warning restore CS1591
    }
}
