// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RLDType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "D_TYPE_UNSPECIFIED")]
        #pragma warning disable CS1591
        D_TYPE_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "D_TYPE_INT64")]
        #pragma warning disable CS1591
        D_TYPE_INT64,
        #pragma warning restore CS1591
        [EnumMember(Value = "D_TYPE_FLOAT32")]
        #pragma warning disable CS1591
        D_TYPE_FLOAT32,
        #pragma warning restore CS1591
        [EnumMember(Value = "D_TYPE_BFLOAT16")]
        #pragma warning disable CS1591
        D_TYPE_BFLOAT16,
        #pragma warning restore CS1591
    }
}
