// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RlGrpoLossParams : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agg_type property</summary>
        public global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossAggregationType? AggType { get; set; }
        /// <summary>KL penalty coefficient</summary>
        public double? Beta { get; set; }
        /// <summary>Upper clip threshold for the importance-sampling ratio. The ratio is clamped to this bound; tighter clipping makes policy updates more conservative. Must be &gt;= 1.</summary>
        public float? ClipHighThreshold { get; set; }
        /// <summary>Lower clip threshold for the importance-sampling ratio. The ratio is clamped to this bound; tighter clipping makes policy updates more conservative. Must be &lt;= 1.</summary>
        public float? ClipLowThreshold { get; set; }
        /// <summary>Controls whether GRPO loss uses token-level or sequence-level importance ratios.</summary>
        public global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossRatioType? RatioType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossParams"/> and sets the default values.
        /// </summary>
        public RlGrpoLossParams()
        {
            AdditionalData = new Dictionary<string, object>();
            Beta = 0;
            ClipHighThreshold = 1.2f;
            ClipLowThreshold = 0.8f;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossParams"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossParams CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossParams();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agg_type", n => { AggType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossAggregationType>(); } },
                { "beta", n => { Beta = n.GetDoubleValue(); } },
                { "clip_high_threshold", n => { ClipHighThreshold = n.GetFloatValue(); } },
                { "clip_low_threshold", n => { ClipLowThreshold = n.GetFloatValue(); } },
                { "ratio_type", n => { RatioType = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossRatioType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossAggregationType>("agg_type", AggType);
            writer.WriteDoubleValue("beta", Beta);
            writer.WriteFloatValue("clip_high_threshold", ClipHighThreshold);
            writer.WriteFloatValue("clip_low_threshold", ClipLowThreshold);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossRatioType>("ratio_type", RatioType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
