// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RlLossType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "LOSS_TYPE_UNSPECIFIED")]
        #pragma warning disable CS1591
        LossTypeUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOSS_TYPE_CROSS_ENTROPY")]
        #pragma warning disable CS1591
        LossTypeCrossEntropy,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOSS_TYPE_GRPO")]
        #pragma warning disable CS1591
        LossTypeGrpo,
        #pragma warning restore CS1591
    }
}
