// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Token-level inputs used to compute the loss for one training sample.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RlLossInputs : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cispo_inputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlCispoLossInputs? CispoInputs { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlCispoLossInputs CispoInputs { get; set; }
#endif
        /// <summary>The dro_inputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlDroLossInputs? DroInputs { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlDroLossInputs DroInputs { get; set; }
#endif
        /// <summary>The grpo_inputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossInputs? GrpoInputs { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossInputs GrpoInputs { get; set; }
#endif
        /// <summary>Loss inputs for unclipped importance-sampling policy-gradient updates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlImportanceSamplingLossInputs? ImportanceSamplingInputs { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlImportanceSamplingLossInputs ImportanceSamplingInputs { get; set; }
#endif
        /// <summary>The ppo_inputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlPpoLossInputs? PpoInputs { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlPpoLossInputs PpoInputs { get; set; }
#endif
        /// <summary>Mixture-of-experts routing decisions captured while generating, so training can reuse the same expert selection. A contiguous uint16 buffer of selected expert indices, reshaped by `shape`, which is always `[num_tokens, num_layers, topk]`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlRoutedExperts? RoutedExperts { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlRoutedExperts RoutedExperts { get; set; }
#endif
        /// <summary>The target_tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlLossTargetTokens? TargetTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlLossTargetTokens TargetTokens { get; set; }
#endif
        /// <summary>The weights property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RlWeights? Weights { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RlWeights Weights { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.RlLossInputs"/> and sets the default values.
        /// </summary>
        public RlLossInputs()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.RlLossInputs"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.RlLossInputs CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.RlLossInputs();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cispo_inputs", n => { CispoInputs = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlCispoLossInputs>(global::Soenneker.Together.OpenApiClient.Models.RlCispoLossInputs.CreateFromDiscriminatorValue); } },
                { "dro_inputs", n => { DroInputs = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlDroLossInputs>(global::Soenneker.Together.OpenApiClient.Models.RlDroLossInputs.CreateFromDiscriminatorValue); } },
                { "grpo_inputs", n => { GrpoInputs = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossInputs>(global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossInputs.CreateFromDiscriminatorValue); } },
                { "importance_sampling_inputs", n => { ImportanceSamplingInputs = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlImportanceSamplingLossInputs>(global::Soenneker.Together.OpenApiClient.Models.RlImportanceSamplingLossInputs.CreateFromDiscriminatorValue); } },
                { "ppo_inputs", n => { PpoInputs = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlPpoLossInputs>(global::Soenneker.Together.OpenApiClient.Models.RlPpoLossInputs.CreateFromDiscriminatorValue); } },
                { "routed_experts", n => { RoutedExperts = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlRoutedExperts>(global::Soenneker.Together.OpenApiClient.Models.RlRoutedExperts.CreateFromDiscriminatorValue); } },
                { "target_tokens", n => { TargetTokens = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlLossTargetTokens>(global::Soenneker.Together.OpenApiClient.Models.RlLossTargetTokens.CreateFromDiscriminatorValue); } },
                { "weights", n => { Weights = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlWeights>(global::Soenneker.Together.OpenApiClient.Models.RlWeights.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlCispoLossInputs>("cispo_inputs", CispoInputs);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlDroLossInputs>("dro_inputs", DroInputs);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlGrpoLossInputs>("grpo_inputs", GrpoInputs);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlImportanceSamplingLossInputs>("importance_sampling_inputs", ImportanceSamplingInputs);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlPpoLossInputs>("ppo_inputs", PpoInputs);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlRoutedExperts>("routed_experts", RoutedExperts);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlLossTargetTokens>("target_tokens", TargetTokens);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RlWeights>("weights", Weights);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
