// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Async sample operation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RLSampleOperation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Error details for a failed training operation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationError Error { get; set; }
#endif
        /// <summary>Operation ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Result of a sample operation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.RLSampleResult? Output { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.RLSampleResult Output { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.RLSampleOperation"/> and sets the default values.
        /// </summary>
        public RLSampleOperation()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationStatus.TRAINING_OPERATION_STATUS_UNSPECIFIED;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.RLSampleOperation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.RLSampleOperation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.RLSampleOperation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationError>(global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationError.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "output", n => { Output = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.RLSampleResult>(global::Soenneker.Together.OpenApiClient.Models.RLSampleResult.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationError>("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.RLSampleResult>("output", Output);
            writer.WriteEnumValue<global::Soenneker.Together.OpenApiClient.Models.RLTrainingOperationStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
