// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Reason generation stopped.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RlStopReason
    {
        [EnumMember(Value = "STOP_REASON_LENGTH")]
        #pragma warning disable CS1591
        StopReasonLength,
        #pragma warning restore CS1591
        [EnumMember(Value = "STOP_REASON_STOP")]
        #pragma warning disable CS1591
        StopReasonStop,
        #pragma warning restore CS1591
    }
}
