// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>GPU type used when model-resource creation omits gpu_type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RlSupportedModelDefaultGpuType
    {
        [EnumMember(Value = "H100-80GB")]
        #pragma warning disable CS1591
        H10080Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "B200-SXM")]
        #pragma warning disable CS1591
        B200Sxm,
        #pragma warning restore CS1591
    }
}
