// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RlTrainingOperationErrorCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TRAINING_OPERATION_ERROR_CODE_UNSPECIFIED")]
        #pragma warning disable CS1591
        TrainingOperationErrorCodeUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_OPERATION_ERROR_CODE_RESOURCE_EXHAUSTED")]
        #pragma warning disable CS1591
        TrainingOperationErrorCodeResourceExhausted,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_OPERATION_ERROR_CODE_TIMEOUT")]
        #pragma warning disable CS1591
        TrainingOperationErrorCodeTimeout,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_OPERATION_ERROR_CODE_INTERNAL_ERROR")]
        #pragma warning disable CS1591
        TrainingOperationErrorCodeInternalError,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_OPERATION_ERROR_CODE_SESSION_NOT_ACTIVE")]
        #pragma warning disable CS1591
        TrainingOperationErrorCodeSessionNotActive,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAINING_OPERATION_ERROR_CODE_INVALID_INPUT")]
        #pragma warning disable CS1591
        TrainingOperationErrorCodeInvalidInput,
        #pragma warning restore CS1591
    }
}
