// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>Filter models to those with a deployment profile in the selected adapter serving mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SupportedModelsServiceListSupportedModelsAdapterModeParameter
    {
        [EnumMember(Value = "ADAPTER_MODE_FIXED")]
        #pragma warning disable CS1591
        AdapterModeFixed,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADAPTER_MODE_DYNAMIC")]
        #pragma warning disable CS1591
        AdapterModeDynamic,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADAPTER_MODE_DISABLED")]
        #pragma warning disable CS1591
        AdapterModeDisabled,
        #pragma warning restore CS1591
    }
}
