// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ToolChoice_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "function")]
        #pragma warning disable CS1591
        Function,
        #pragma warning restore CS1591
    }
}
