// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>GPUType specifies the GPU hardware to use (e.g., &quot;h100-80gb&quot;)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateDeploymentRequest_gpu_type
    {
        [EnumMember(Value = "h100-80gb")]
        #pragma warning disable CS1591
        H10080gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "h100-40gb-mig")]
        #pragma warning disable CS1591
        H10040gbMig,
        #pragma warning restore CS1591
        [EnumMember(Value = "b200-192gb")]
        #pragma warning disable CS1591
        B200192gb,
        #pragma warning restore CS1591
    }
}
