// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Contains all media inputs for video generation. Accepted fields depend on the model type.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideoMedia : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of audio inputs. Each element accepts a URL string or an object with an &quot;audio&quot; key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs>? AudioInputs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs> AudioInputs { get; set; }
#endif
        /// <summary>Array of images to guide video generation at specific timeline positions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInput>? FrameImages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInput> FrameImages { get; set; }
#endif
        /// <summary>Array of video clips to use as starting clips.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoRef>? FrameVideos { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoRef> FrameVideos { get; set; }
#endif
        /// <summary>Array of image URLs that guide the general appearance across the video.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReferenceImages { get; set; }
#nullable restore
#else
        public List<string> ReferenceImages { get; set; }
#endif
        /// <summary>Array of reference videos.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoRef>? ReferenceVideos { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Together.OpenApiClient.Models.VideoRef> ReferenceVideos { get; set; }
#endif
        /// <summary>Source video to edit. Accepts a URL string or an object with a &quot;video&quot; key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.VideoMediaSourceVideo? SourceVideo { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.VideoMediaSourceVideo SourceVideo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoMedia"/> and sets the default values.
        /// </summary>
        public VideoMedia()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoMedia"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.VideoMedia CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Together.OpenApiClient.Models.VideoMedia();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audio_inputs", n => { AudioInputs = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs>(global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs.CreateFromDiscriminatorValue)?.AsList(); } },
                { "frame_images", n => { FrameImages = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInput>(global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInput.CreateFromDiscriminatorValue)?.AsList(); } },
                { "frame_videos", n => { FrameVideos = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoRef>(global::Soenneker.Together.OpenApiClient.Models.VideoRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reference_images", n => { ReferenceImages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "reference_videos", n => { ReferenceVideos = n.GetCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoRef>(global::Soenneker.Together.OpenApiClient.Models.VideoRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "source_video", n => { SourceVideo = n.GetObjectValue<global::Soenneker.Together.OpenApiClient.Models.VideoMediaSourceVideo>(global::Soenneker.Together.OpenApiClient.Models.VideoMediaSourceVideo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs>("audio_inputs", AudioInputs);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInput>("frame_images", FrameImages);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoRef>("frame_videos", FrameVideos);
            writer.WriteCollectionOfPrimitiveValues<string>("reference_images", ReferenceImages);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Together.OpenApiClient.Models.VideoRef>("reference_videos", ReferenceVideos);
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.VideoMediaSourceVideo>("source_video", SourceVideo);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Together.OpenApiClient.Models.AudioRef"/>, <see cref="global::Soenneker.Together.OpenApiClient.Models.UnionBranch"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VideoMedia_audio_inputs : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.AudioRef"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Together.OpenApiClient.Models.AudioRef? AudioRef { get; set; }
#nullable restore
#else
            public global::Soenneker.Together.OpenApiClient.Models.AudioRef AudioRef { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.UnionBranch"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Together.OpenApiClient.Models.UnionBranch? UnionBranch { get; set; }
#nullable restore
#else
            public global::Soenneker.Together.OpenApiClient.Models.UnionBranch UnionBranch { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Together.OpenApiClient.Models.VideoMedia.VideoMedia_audio_inputs();
                if("AudioRef".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AudioRef = new global::Soenneker.Together.OpenApiClient.Models.AudioRef();
                }
                else if("UnionBranch".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UnionBranch = new global::Soenneker.Together.OpenApiClient.Models.UnionBranch();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AudioRef != null)
                {
                    return AudioRef.GetFieldDeserializers();
                }
                else if(UnionBranch != null)
                {
                    return UnionBranch.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(AudioRef != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.AudioRef>(null, AudioRef);
                }
                else if(UnionBranch != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.UnionBranch>(null, UnionBranch);
                }
            }
        }
    }
}
#pragma warning restore CS0618
