// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Together.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Branch1"/>, <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Wrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideoFrameImageInputFrame : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Branch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Branch1? VideoFrameImageInputFrameBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Branch1 VideoFrameImageInputFrameBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Wrapper? VideoFrameImageInputFrameWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Wrapper VideoFrameImageInputFrameWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame();
            result.VideoFrameImageInputFrameBranch1 = new global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Branch1();
            result.VideoFrameImageInputFrameWrapper = new global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Wrapper();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(VideoFrameImageInputFrameBranch1 != null || VideoFrameImageInputFrameWrapper != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(VideoFrameImageInputFrameBranch1, VideoFrameImageInputFrameWrapper);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Together.OpenApiClient.Models.VideoFrameImageInputFrame_Branch1>(null, VideoFrameImageInputFrameBranch1, VideoFrameImageInputFrameWrapper);
        }
    }
}
#pragma warning restore CS0618
