// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Models;
using Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward
{
    /// <summary>
    /// Builds and executes requests for operations under \rl\training-sessions\{session_id}\operations\forward
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ForwardRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Together.OpenApiClient.rl.trainingSessions.item.operations.forward.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.Item.WithOperation_ItemRequestBuilder"/></returns>
        public global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.Item.WithOperation_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("operation_id", position);
                return new global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.Item.WithOperation_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.ForwardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl/training-sessions/{session_id}/operations/forward", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.ForwardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl/training-sessions/{session_id}/operations/forward", rawUrl)
        {
        }
        /// <summary>
        /// Submits a forward operation that will asynchronously run a no-grad forward pass and return per-token log-probabilities for each sample.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.RLForwardOperation"/></returns>
        /// <param name="body">Request body for a forward pass.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.ErrorData">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Together.OpenApiClient.Models.RLForwardOperation?> PostAsync(global::Soenneker.Together.OpenApiClient.Models.RLForwardBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Together.OpenApiClient.Models.RLForwardOperation> PostAsync(global::Soenneker.Together.OpenApiClient.Models.RLForwardBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Together.OpenApiClient.Models.ErrorData.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Together.OpenApiClient.Models.RLForwardOperation>(requestInfo, global::Soenneker.Together.OpenApiClient.Models.RLForwardOperation.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Submits a forward operation that will asynchronously run a no-grad forward pass and return per-token log-probabilities for each sample.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for a forward pass.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Together.OpenApiClient.Models.RLForwardBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Together.OpenApiClient.Models.RLForwardBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.ForwardRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.ForwardRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Together.OpenApiClient.Rl.TrainingSessions.Item.Operations.Forward.ForwardRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
