// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Audio.Speech.Websocket
{
    /// <summary>The TTS model to use for speech generation. Can also be set via `tts_session.updated` event.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetModelQueryParameterType
    {
        [EnumMember(Value = "hexgrad/Kokoro-82M")]
        #pragma warning disable CS1591
        HexgradKokoro82M,
        #pragma warning restore CS1591
        [EnumMember(Value = "cartesia/sonic-english")]
        #pragma warning disable CS1591
        CartesiaSonicEnglish,
        #pragma warning restore CS1591
    }
}
