// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop
{
    /// <summary>
    /// Builds and executes requests for operations under \rl\model-resources\{modelResourcesId}\stop
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StopRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StopRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl/model-resources/{modelResourcesId}/stop{?force*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StopRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl/model-resources/{modelResourcesId}/stop{?force*}", rawUrl)
        {
        }
        /// <summary>
        /// Stops every session attached to the resource and tears down its GPU pods.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.RlModelResources"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.ErrorData">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Together.OpenApiClient.Models.RlModelResources?> PostAsync(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder.StopRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Together.OpenApiClient.Models.RlModelResources> PostAsync(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder.StopRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Together.OpenApiClient.Models.ErrorData.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Together.OpenApiClient.Models.RlModelResources>(requestInfo, global::Soenneker.Together.OpenApiClient.Models.RlModelResources.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Stops every session attached to the resource and tears down its GPU pods.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder.StopRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder.StopRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Together.OpenApiClient.Rl.ModelResources.Item.Stop.StopRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Stops every session attached to the resource and tears down its GPU pods.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StopRequestBuilderPostQueryParameters 
        {
            [QueryParameter("force")]
            public bool? Force { get; set; }
        }
    }
}
#pragma warning restore CS0618
