// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Together.OpenApiClient.Realtime
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetInput_audio_formatQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "pcm_s16le_16000")]
        #pragma warning disable CS1591
        Pcm_s16le_16000,
        #pragma warning restore CS1591
    }
}
