// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Queue.Cancel;
using Soenneker.Together.OpenApiClient.Queue.Metrics;
using Soenneker.Together.OpenApiClient.Queue.Status;
using Soenneker.Together.OpenApiClient.Queue.Submit;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Together.OpenApiClient.Queue
{
    /// <summary>
    /// Builds and executes requests for operations under \queue
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueueRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::Soenneker.Together.OpenApiClient.Queue.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Soenneker.Together.OpenApiClient.Queue.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::Soenneker.Together.OpenApiClient.Queue.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::Soenneker.Together.OpenApiClient.Queue.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.Together.OpenApiClient.Queue.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.Together.OpenApiClient.Queue.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The submit property</summary>
        public global::Soenneker.Together.OpenApiClient.Queue.Submit.SubmitRequestBuilder Submit
        {
            get => new global::Soenneker.Together.OpenApiClient.Queue.Submit.SubmitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Queue.QueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueueRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/queue", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Queue.QueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueueRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/queue", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
