// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{projectId}\endpoints\{endpoint-id}\deployments\{deployment-id}\adapters\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdaptersItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdaptersItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/endpoints/{endpoint%2Did}/deployments/{deployment%2Did}/adapters/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdaptersItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/endpoints/{endpoint%2Did}/deployments/{deployment%2Did}/adapters/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Detaches an adapter from a deployment using its row-level etag for optimistic concurrency.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeploymentServiceRemoveAdapter200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.ErrorData">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Together.OpenApiClient.Models.DeploymentServiceRemoveAdapter200Response?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder.AdaptersItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Together.OpenApiClient.Models.DeploymentServiceRemoveAdapter200Response> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder.AdaptersItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Together.OpenApiClient.Models.ErrorData.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Together.OpenApiClient.Models.DeploymentServiceRemoveAdapter200Response>(requestInfo, global::Soenneker.Together.OpenApiClient.Models.DeploymentServiceRemoveAdapter200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets an attached adapter and its per-cluster load state.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.ErrorData">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Together.OpenApiClient.Models.ErrorData.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry>(requestInfo, global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the pinned revision of an attached adapter using its row-level etag for optimistic concurrency.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry"/></returns>
        /// <param name="body">Request body for updating an adapter.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.ErrorData">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry?> PatchAsync(global::Soenneker.Together.OpenApiClient.Models.DeUpdateAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry> PatchAsync(global::Soenneker.Together.OpenApiClient.Models.DeUpdateAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Together.OpenApiClient.Models.ErrorData.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry>(requestInfo, global::Soenneker.Together.OpenApiClient.Models.DeAdapterEntry.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Detaches an adapter from a deployment using its row-level etag for optimistic concurrency.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder.AdaptersItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder.AdaptersItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, "{+baseurl}/projects/{projectId}/endpoints/{endpoint%2Did}/deployments/{deployment%2Did}/adapters/{id}?etag={etag}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Gets an attached adapter and its per-cluster load state.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates the pinned revision of an attached adapter using its row-level etag for optimistic concurrency.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for updating an adapter.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Together.OpenApiClient.Models.DeUpdateAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Together.OpenApiClient.Models.DeUpdateAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Together.OpenApiClient.Projects.Item.Endpoints.Item.Deployments.Item.Adapters.Item.AdaptersItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Detaches an adapter from a deployment using its row-level etag for optimistic concurrency.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AdaptersItemRequestBuilderDeleteQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("etag")]
            public string? Etag { get; set; }
#nullable restore
#else
            [QueryParameter("etag")]
            public string Etag { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
