// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Together.OpenApiClient.FineTunes.Preview
{
    /// <summary>
    /// Builds and executes requests for operations under \fine-tunes\preview
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PreviewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.FineTunes.Preview.PreviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PreviewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fine-tunes/preview", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.FineTunes.Preview.PreviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PreviewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fine-tunes/preview", rawUrl)
        {
        }
        /// <summary>
        /// Preview how sampled rows from a fine-tuning training file will be tokenized before packing.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewResponse"/></returns>
        /// <param name="body">Request body for previewing tokenized fine-tuning data.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.ErrorData">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.ErrorData">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewMessageError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewMessageError">When receiving a 502 status code</exception>
        /// <exception cref="global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewDetailError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewResponse?> PostAsync(global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewResponse> PostAsync(global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Together.OpenApiClient.Models.ErrorData.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Together.OpenApiClient.Models.ErrorData.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewMessageError.CreateFromDiscriminatorValue },
                { "502", global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewMessageError.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewDetailError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewResponse>(requestInfo, global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Preview how sampled rows from a fine-tuning training file will be tokenized before packing.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for previewing tokenized fine-tuning data.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Together.OpenApiClient.Models.FineTunePreviewRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.FineTunes.Preview.PreviewRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Together.OpenApiClient.FineTunes.Preview.PreviewRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Together.OpenApiClient.FineTunes.Preview.PreviewRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
