// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Together.OpenApiClient.Audio;
using Soenneker.Together.OpenApiClient.Batches;
using Soenneker.Together.OpenApiClient.Chat;
using Soenneker.Together.OpenApiClient.Clusters;
using Soenneker.Together.OpenApiClient.Completions;
using Soenneker.Together.OpenApiClient.Compute;
using Soenneker.Together.OpenApiClient.Deployments;
using Soenneker.Together.OpenApiClient.Embeddings;
using Soenneker.Together.OpenApiClient.Endpoints;
using Soenneker.Together.OpenApiClient.Evaluation;
using Soenneker.Together.OpenApiClient.Files;
using Soenneker.Together.OpenApiClient.FineTunes;
using Soenneker.Together.OpenApiClient.Finetune;
using Soenneker.Together.OpenApiClient.Hardware;
using Soenneker.Together.OpenApiClient.Images;
using Soenneker.Together.OpenApiClient.Jobs;
using Soenneker.Together.OpenApiClient.ModelsRequests;
using Soenneker.Together.OpenApiClient.Queue;
using Soenneker.Together.OpenApiClient.Realtime;
using Soenneker.Together.OpenApiClient.Rerank;
using Soenneker.Together.OpenApiClient.Rl;
using Soenneker.Together.OpenApiClient.Tci;
using Soenneker.Together.OpenApiClient.Videos;
using Soenneker.Together.OpenApiClient.Voices;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Together.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TogetherOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The audio property</summary>
        public global::Soenneker.Together.OpenApiClient.Audio.AudioRequestBuilder Audio
        {
            get => new global::Soenneker.Together.OpenApiClient.Audio.AudioRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batches property</summary>
        public global::Soenneker.Together.OpenApiClient.Batches.BatchesRequestBuilder Batches
        {
            get => new global::Soenneker.Together.OpenApiClient.Batches.BatchesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chat property</summary>
        public global::Soenneker.Together.OpenApiClient.Chat.ChatRequestBuilder Chat
        {
            get => new global::Soenneker.Together.OpenApiClient.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clusters property</summary>
        public global::Soenneker.Together.OpenApiClient.Clusters.ClustersRequestBuilder Clusters
        {
            get => new global::Soenneker.Together.OpenApiClient.Clusters.ClustersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The completions property</summary>
        public global::Soenneker.Together.OpenApiClient.Completions.CompletionsRequestBuilder Completions
        {
            get => new global::Soenneker.Together.OpenApiClient.Completions.CompletionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compute property</summary>
        public global::Soenneker.Together.OpenApiClient.Compute.ComputeRequestBuilder Compute
        {
            get => new global::Soenneker.Together.OpenApiClient.Compute.ComputeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deployments property</summary>
        public global::Soenneker.Together.OpenApiClient.Deployments.DeploymentsRequestBuilder Deployments
        {
            get => new global::Soenneker.Together.OpenApiClient.Deployments.DeploymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The embeddings property</summary>
        public global::Soenneker.Together.OpenApiClient.Embeddings.EmbeddingsRequestBuilder Embeddings
        {
            get => new global::Soenneker.Together.OpenApiClient.Embeddings.EmbeddingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The endpoints property</summary>
        public global::Soenneker.Together.OpenApiClient.Endpoints.EndpointsRequestBuilder Endpoints
        {
            get => new global::Soenneker.Together.OpenApiClient.Endpoints.EndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The evaluation property</summary>
        public global::Soenneker.Together.OpenApiClient.Evaluation.EvaluationRequestBuilder Evaluation
        {
            get => new global::Soenneker.Together.OpenApiClient.Evaluation.EvaluationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Soenneker.Together.OpenApiClient.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Together.OpenApiClient.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The finetune property</summary>
        public global::Soenneker.Together.OpenApiClient.Finetune.FinetuneRequestBuilder Finetune
        {
            get => new global::Soenneker.Together.OpenApiClient.Finetune.FinetuneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fineTunes property</summary>
        public global::Soenneker.Together.OpenApiClient.FineTunes.FineTunesRequestBuilder FineTunes
        {
            get => new global::Soenneker.Together.OpenApiClient.FineTunes.FineTunesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hardware property</summary>
        public global::Soenneker.Together.OpenApiClient.Hardware.HardwareRequestBuilder Hardware
        {
            get => new global::Soenneker.Together.OpenApiClient.Hardware.HardwareRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The images property</summary>
        public global::Soenneker.Together.OpenApiClient.Images.ImagesRequestBuilder Images
        {
            get => new global::Soenneker.Together.OpenApiClient.Images.ImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Soenneker.Together.OpenApiClient.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Soenneker.Together.OpenApiClient.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The models property</summary>
        public global::Soenneker.Together.OpenApiClient.ModelsRequests.ModelsRequestBuilder Models
        {
            get => new global::Soenneker.Together.OpenApiClient.ModelsRequests.ModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queue property</summary>
        public global::Soenneker.Together.OpenApiClient.Queue.QueueRequestBuilder Queue
        {
            get => new global::Soenneker.Together.OpenApiClient.Queue.QueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The realtime property</summary>
        public global::Soenneker.Together.OpenApiClient.Realtime.RealtimeRequestBuilder Realtime
        {
            get => new global::Soenneker.Together.OpenApiClient.Realtime.RealtimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rerank property</summary>
        public global::Soenneker.Together.OpenApiClient.Rerank.RerankRequestBuilder Rerank
        {
            get => new global::Soenneker.Together.OpenApiClient.Rerank.RerankRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rl property</summary>
        public global::Soenneker.Together.OpenApiClient.Rl.RlRequestBuilder Rl
        {
            get => new global::Soenneker.Together.OpenApiClient.Rl.RlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tci property</summary>
        public global::Soenneker.Together.OpenApiClient.Tci.TciRequestBuilder Tci
        {
            get => new global::Soenneker.Together.OpenApiClient.Tci.TciRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The videos property</summary>
        public global::Soenneker.Together.OpenApiClient.Videos.VideosRequestBuilder Videos
        {
            get => new global::Soenneker.Together.OpenApiClient.Videos.VideosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The voices property</summary>
        public global::Soenneker.Together.OpenApiClient.Voices.VoicesRequestBuilder Voices
        {
            get => new global::Soenneker.Together.OpenApiClient.Voices.VoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.TogetherOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TogetherOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.together.xyz/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
