// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Rl.Checkpoints.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Together.OpenApiClient.Rl.Checkpoints
{
    /// <summary>
    /// Builds and executes requests for operations under \rl\checkpoints
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CheckpointsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Together.OpenApiClient.rl.checkpoints.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Together.OpenApiClient.Rl.Checkpoints.Item.CheckpointsItemRequestBuilder"/></returns>
        public global::Soenneker.Together.OpenApiClient.Rl.Checkpoints.Item.CheckpointsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Together.OpenApiClient.Rl.Checkpoints.Item.CheckpointsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Rl.Checkpoints.CheckpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CheckpointsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl/checkpoints", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Rl.Checkpoints.CheckpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CheckpointsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl/checkpoints", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
