// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Together.OpenApiClient.Compute.Clusters.Item.Instances.Item.Remediations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Together.OpenApiClient.Compute.Clusters.Item.Instances.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \compute\clusters\{cluster_id}\instances\{instance_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithInstance_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The remediations property</summary>
        public global::Soenneker.Together.OpenApiClient.Compute.Clusters.Item.Instances.Item.Remediations.RemediationsRequestBuilder Remediations
        {
            get => new global::Soenneker.Together.OpenApiClient.Compute.Clusters.Item.Instances.Item.Remediations.RemediationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Compute.Clusters.Item.Instances.Item.WithInstance_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInstance_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/compute/clusters/{cluster_id}/instances/{instance_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Together.OpenApiClient.Compute.Clusters.Item.Instances.Item.WithInstance_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInstance_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/compute/clusters/{cluster_id}/instances/{instance_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
